In [1]:
from atrader import *
import pandas as pd
import numpy as np

code = get_code_list_set('SZAG','2005-01-01','2019-05-31')
data = pd.read_csv('../data/szag_050101_190531.csv')
data = data.merge(code[['code','name']], on='code')

In [57]:
def get_asset_code(df,name_col,thresh_hold):
    count_trade = df.groupby('name',as_index=False).agg({'close':'count'})
    count_trade = count_trade[count_trade.close>thresh_hold]
    count_trade['is_ST_or_S'] = count_trade['name'].apply(lambda x: 1 \
                                                          if x.startswith('*') or x.startswith('S') else 0)
    count_trade = count_trade[count_trade.is_ST_or_S==0]
    return count_trade

def get_valid_asset(df,asset_code,last_date):
    df = df[df.name.isin(asset_code)]
    df = df.sort_values(['time'])
    last_trade_time = df.groupby(['name'],as_index=False)['time'].last()
    last_trade_time['time'] = pd.to_datetime(last_trade_time['time'], format='%Y-%m-%d')
    last_trade_time = last_trade_time[last_trade_time.time>=pd.to_datetime(last_date)]
    return last_trade_time

In [53]:
asset_code = get_asset_code(data,'name',3000)
valid_asset = get_valid_asset(data, asset_code.name.unique(), '2019-05-28 15:00:00')
data = data.merge(valid_asset[['name']], on='name')

                        time        code     open     high      low    close     volume       amount  open_interest   name
0        2005-01-04 15:00:00  sse.600000  0.88184  0.88184  0.86162  0.86920    38089.0  2.61349e+07            NaN  浦发银行
1        2005-01-05 15:00:00  sse.600000  0.86920  0.86920  0.84899  0.85530    52252.0  3.53668e+07            NaN  浦发银行
2        2005-01-06 15:00:00  sse.600000  0.85909  0.86288  0.83762  0.84393    42980.0  2.87582e+07            NaN  浦发银行
3        2005-01-07 15:00:00  sse.600000  0.84393  0.85404  0.84014  0.84646    43628.0  2.92392e+07            NaN  浦发银行
4        2005-01-10 15:00:00  sse.600000  0.85909  0.87804  0.85025  0.87552    71152.0  4.87984e+07            NaN  浦发银行
5        2005-01-11 15:00:00  sse.600000  0.87552  0.88689  0.87173  0.88563    68951.0  4.80392e+07            NaN  浦发银行
6        2005-01-12 15:00:00  sse.600000  0.88689  0.88815  0.87299  0.88057    27974.0  1.94477e+07            NaN  浦发银行
7        2005-01-13 15:00:00  sse.600000  0.87804  0.88689  0.87678  0.87931    12848.0  8.97678e+06            NaN  浦发银行
8        2005-01-14 15:00:00  sse.600000  0.87931  0.89447  0.87173  0.87425    17310.0  1.21088e+07            NaN  浦发银行
9        2005-01-17 15:00:00  sse.600000  0.87173  0.87425  0.85783  0.85909    26207.0  1.79150e+07            NaN  浦发银行
10       2005-01-18 15:00:00  sse.600000  0.85909  0.86920  0.85025  0.86920    15958.0  1.08510e+07            NaN  浦发银行
11       2005-01-19 15:00:00  sse.600000  0.86920  0.86920  0.85404  0.85657    10293.0  7.01240e+06            NaN  浦发银行
12       2005-01-20 15:00:00  sse.600000  0.85278  0.85657  0.84014  0.84899    21105.0  1.41791e+07            NaN  浦发银行
13       2005-01-21 15:00:00  sse.600000  0.84899  0.93363  0.84646  0.93363   413736.0  3.01115e+08            NaN  浦发银行
14       2005-01-24 15:00:00  sse.600000  0.96901  0.98038  0.93742  0.96648   467508.0  3.54409e+08            NaN  浦发银行
15       2005-01-25 15:00:00  sse.600000  0.95385  0.95511  0.92984  0.94374   267952.0  1.99832e+08            NaN  浦发银行
16       2005-01-26 15:00:00  sse.600000  0.94374  0.95890  0.93237  0.93742   162307.0  1.21821e+08            NaN  浦发银行
17       2005-01-27 15:00:00  sse.600000  0.93363  0.94879  0.91595  0.92226   108079.0  7.97692e+07            NaN  浦发银行
18       2005-01-28 15:00:00  sse.600000  0.91974  0.94248  0.91089  0.93995   104111.0  7.63250e+07            NaN  浦发银行
19       2005-01-31 15:00:00  sse.600000  0.93490  0.93995  0.91974  0.93111    76625.0  5.64869e+07            NaN  浦发银行
20       2005-02-01 15:00:00  sse.600000  0.92984  0.95511  0.92479  0.94753   114257.0  8.55920e+07            NaN  浦发银行
21       2005-02-02 15:00:00  sse.600000  0.94753  1.00438  0.94248  0.99554   239071.0  1.85037e+08            NaN  浦发银行
22       2005-02-03 15:00:00  sse.600000  0.99554  0.99807  0.96395  0.96774   137771.0  1.07341e+08            NaN  浦发银行
23       2005-02-04 15:00:00  sse.600000  0.96774  1.04860  0.96016  1.02586   241703.0  1.93804e+08            NaN  浦发银行
24       2005-02-16 15:00:00  sse.600000  1.03091  1.04607  1.01196  1.01575   127186.0  1.03755e+08            NaN  浦发银行
25       2005-02-17 15:00:00  sse.600000  1.01575  1.01575  0.98543  0.99428   115673.0  9.12565e+07            NaN  浦发银行
26       2005-02-18 15:00:00  sse.600000  0.99554  1.00565  0.97911  0.98543    80919.0  6.34333e+07            NaN  浦发银行
27       2005-02-21 15:00:00  sse.600000  1.00438  1.02586  0.99175  1.01954   168369.0  1.35085e+08            NaN  浦发银行
28       2005-02-22 15:00:00  sse.600000  1.01954  1.03344  1.00944  1.02460   103037.0  8.32614e+07            NaN  浦发银行
29       2005-02-23 15:00:00  sse.600000  1.02460  1.02460  0.99554  0.99933   153736.0  1.22680e+08            NaN  浦发银行
30       2005-02-24 15:00:00  sse.600000  0.99807  1.01449  0.99049  0.99554   101869.0  8.06854e+07            NaN  浦发银行
31       2005-02-25 15:00:00  sse.600000  1.00438  1.02460  0.99807  1.00691   114734.0  9.22027e+07            NaN  浦发银行
32       2005-02-28 15:00:00  sse.600000  1.00438  1.00438  0.96774  0.97785   174378.0  1.34890e+08            NaN  浦发银行
33       2005-03-01 15:00:00  sse.600000  0.97911  0.97911  0.95637  0.96269   109238.0  8.34199e+07            NaN  浦发银行
34       2005-03-02 15:00:00  sse.600000  0.96269  0.97532  0.95385  0.96016    88165.0  6.71945e+07            NaN  浦发银行
35       2005-03-03 15:00:00  sse.600000  0.96016  0.97785  0.95764  0.97659    62803.0  4.82129e+07            NaN  浦发银行
36       2005-03-04 15:00:00  sse.600000  0.97659  0.97785  0.96143  0.96774    50817.0  3.89365e+07            NaN  浦发银行
37       2005-03-07 15:00:00  sse.600000  0.96269  0.97406  0.96016  0.96648    28201.0  2.15504e+07            NaN  浦发银行
38       2005-03-08 15:00:00  sse.600000  0.97153  0.98670  0.94753  0.98290   131323.0  1.00582e+08            NaN  浦发银行
39       2005-03-09 15:00:00  sse.600000  0.98290  0.98543  0.95385  0.95637   131850.0  1.00634e+08            NaN  浦发银行
40       2005-03-10 15:00:00  sse.600000  0.96016  0.96774  0.93490  0.94121    83274.0  6.29009e+07            NaN  浦发银行
41       2005-03-11 15:00:00  sse.600000  0.94121  0.95258  0.93237  0.93616    58579.0  4.35563e+07            NaN  浦发银行
42       2005-03-14 15:00:00  sse.600000  0.93742  0.94121  0.91595  0.93111    70780.0  5.20375e+07            NaN  浦发银行
43       2005-03-15 15:00:00  sse.600000  0.93237  0.93490  0.90079  0.90458    76734.0  5.53964e+07            NaN  浦发银行
44       2005-03-16 15:00:00  sse.600000  0.90458  0.91216  0.90079  0.90458    51493.0  3.69706e+07            NaN  浦发银行
45       2005-03-17 15:00:00  sse.600000  0.90710  0.91847  0.90079  0.90079    63910.0  4.60114e+07            NaN  浦发银行
46       2005-03-18 15:00:00  sse.600000  0.90079  0.91847  0.89952  0.90837    53242.0  3.83110e+07            NaN  浦发银行
47       2005-03-21 15:00:00  sse.600000  0.90963  0.91974  0.90458  0.91468    35636.0  2.57780e+07            NaN  浦发银行
48       2005-03-22 15:00:00  sse.600000  0.91468  0.91468  0.86288  0.86415    89448.0  6.22922e+07            NaN  浦发银行
49       2005-03-23 15:00:00  sse.600000  0.86415  0.88563  0.85657  0.87299    74145.0  5.10336e+07            NaN  浦发银行
50       2005-03-24 15:00:00  sse.600000  0.87299  0.87804  0.86036  0.87299    35455.0  2.43980e+07            NaN  浦发银行
51       2005-03-25 15:00:00  sse.600000  0.87299  0.87678  0.86162  0.86667    30011.0  2.06157e+07            NaN  浦发银行
52       2005-03-28 15:00:00  sse.600000  0.86667  0.87173  0.85783  0.87173    29395.0  2.00951e+07            NaN  浦发银行
53       2005-03-29 15:00:00  sse.600000  0.87173  0.88563  0.87173  0.87425    34022.0  2.37140e+07            NaN  浦发银行
54       2005-03-30 15:00:00  sse.600000  0.87425  0.87552  0.85151  0.85278    42913.0  2.91867e+07            NaN  浦发银行
55       2005-03-31 15:00:00  sse.600000  0.85025  0.87552  0.84646  0.87425    39311.0  2.67325e+07            NaN  浦发银行
56       2005-04-01 15:00:00  sse.600000  0.87425  0.93490  0.86288  0.91468   112411.0  7.96997e+07            NaN  浦发银行
57       2005-04-04 15:00:00  sse.600000  0.89068  0.89826  0.87931  0.88436    63074.0  4.44212e+07            NaN  浦发银行
58       2005-04-05 15:00:00  sse.600000  0.88436  0.89068  0.87931  0.88689    25922.0  1.81545e+07            NaN  浦发银行
59       2005-04-06 15:00:00  sse.600000  0.88436  0.90963  0.86541  0.90837    83599.0  5.89540e+07            NaN  浦发银行
60       2005-04-07 15:00:00  sse.600000  0.90963  0.97785  0.90458  0.93490   193899.0  1.44195e+08            NaN  浦发银行
61       2005-04-08 15:00:00  sse.600000  0.93490  0.95764  0.92479  0.95006    99440.0  7.40825e+07            NaN  浦发银行
62       2005-04-11 15:00:00  sse.600000  0.95132  0.97406  0.93742  0.94627   137109.0  1.03727e+08            NaN  浦发银行
63       2005-04-12 15:00:00  sse.600000  0.94500  0.94753  0.92984  0.93237    64879.0  4.81611e+07            NaN  浦发银行
64       2005-04-13 15:00:00  sse.600000  0.93490  0.97153  0.93490  0.94500    93625.0  7.06233e+07            NaN  浦发银行
65       2005-04-14 15:00:00  sse.600000  0.94500  0.95258  0.92605  0.92858    55577.0  4.14330e+07            NaN  浦发银行
66       2005-04-15 15:00:00  sse.600000  0.91974  0.92226  0.90205  0.91721    58009.0  4.17249e+07            NaN  浦发银行
67       2005-04-18 15:00:00  sse.600000  0.90331  0.91595  0.89573  0.90205    50184.0  3.58822e+07            NaN  浦发银行
68       2005-04-19 15:00:00  sse.600000  0.89826  0.91216  0.89826  0.91089    62365.0  4.47085e+07            NaN  浦发银行
69       2005-04-20 15:00:00  sse.600000  0.90837  0.90837  0.86794  0.87299    75755.0  5.26889e+07            NaN  浦发银行
70       2005-04-21 15:00:00  sse.600000  0.87299  0.88436  0.87046  0.87425    37526.0  2.60425e+07            NaN  浦发银行
71       2005-04-22 15:00:00  sse.600000  0.86920  0.88310  0.86541  0.87931    55562.0  3.85444e+07            NaN  浦发银行
72       2005-04-25 15:00:00  sse.600000  0.87299  0.88942  0.87173  0.88436    53920.0  3.76106e+07            NaN  浦发银行
73       2005-04-26 15:00:00  sse.600000  0.88436  0.89826  0.88057  0.88942    34606.0  2.43079e+07            NaN  浦发银行
74       2005-04-28 15:00:00  sse.600000  0.87804  0.87804  0.83383  0.86794    99317.0  6.74569e+07            NaN  浦发银行
75       2005-04-29 15:00:00  sse.600000  0.86667  0.90963  0.85909  0.88689    91394.0  6.40854e+07            NaN  浦发银行
76       2005-05-09 15:00:00  sse.600000  0.89573  0.89700  0.87046  0.87173    44088.0  3.07186e+07            NaN  浦发银行
77       2005-05-10 15:00:00  sse.600000  0.87173  0.89700  0.87046  0.88942    49067.0  3.43526e+07            NaN  浦发银行
78       2005-05-11 15:00:00  sse.600000  0.89068  0.90584  0.88563  0.89194    55283.0  3.92849e+07            NaN  浦发银行
79       2005-05-12 15:00:00  sse.600000  0.90608  0.90608  0.87652  0.87652    54174.0  3.72991e+07            NaN  浦发银行
80       2005-05-13 15:00:00  sse.600000  0.87395  0.89451  0.86752  0.88166    38519.0  2.64141e+07            NaN  浦发银行
81       2005-05-16 15:00:00  sse.600000  0.88038  0.89066  0.86881  0.88423    21429.0  1.46813e+07            NaN  浦发银行
82       2005-05-17 15:00:00  sse.600000  0.88423  0.90479  0.87780  0.89194    29984.0  2.08548e+07            NaN  浦发银行
83       2005-05-18 15:00:00  sse.600000  0.89965  0.90222  0.87909  0.88680    38100.0  2.63058e+07            NaN  浦发银行
84       2005-05-19 15:00:00  sse.600000  0.88809  0.90736  0.88423  0.90479    35161.0  2.45145e+07            NaN  浦发银行
85       2005-05-20 15:00:00  sse.600000  0.90608  0.90736  0.89323  0.89451    22622.0  1.58566e+07            NaN  浦发银行
86       2005-05-23 15:00:00  sse.600000  0.89451  0.89451  0.86752  0.87523    69166.0  4.73951e+07            NaN  浦发银行
87       2005-05-24 15:00:00  sse.600000  0.87009  0.88552  0.86881  0.88038    31534.0  2.15454e+07            NaN  浦发银行
88       2005-05-25 15:00:00  sse.600000  0.88423  0.89451  0.87395  0.87652    31385.0  2.15027e+07            NaN  浦发银行
89       2005-05-26 15:00:00  sse.600000  0.87780  0.88423  0.86110  0.86624    32253.0  2.18780e+07            NaN  浦发银行
90       2005-05-27 15:00:00  sse.600000  0.86624  0.87652  0.85596  0.86110    26402.0  1.78110e+07            NaN  浦发银行
91       2005-05-30 15:00:00  sse.600000  0.86110  0.87395  0.85081  0.87266    19255.0  1.29634e+07            NaN  浦发银行
92       2005-05-31 15:00:00  sse.600000  0.87266  0.87780  0.85853  0.86110    28306.0  1.90853e+07            NaN  浦发银行
93       2005-06-01 15:00:00  sse.600000  0.86110  0.86624  0.84182  0.84696    35054.0  2.31853e+07            NaN  浦发银行
94       2005-06-02 15:00:00  sse.600000  0.84567  0.85467  0.82383  0.83282    66711.0  4.34013e+07            NaN  浦发银行
95       2005-06-03 15:00:00  sse.600000  0.83025  0.85981  0.83025  0.84824    53525.0  3.53498e+07            NaN  浦发银行
96       2005-06-06 15:00:00  sse.600000  0.84696  0.86367  0.83539  0.85853    28445.0  1.87988e+07            NaN  浦发银行
97       2005-06-07 15:00:00  sse.600000  0.86110  0.87395  0.84953  0.85596    34118.0  2.28630e+07            NaN  浦发银行
98       2005-06-08 15:00:00  sse.600000  0.94207  0.94207  0.85981  0.92279   156884.0  1.11515e+08            NaN  浦发银行
99       2005-06-09 15:00:00  sse.600000  0.92279  0.93178  0.90222  0.91508   131936.0  9.39370e+07            NaN  浦发银行
100      2005-06-10 15:00:00  sse.600000  0.91508  0.94721  0.90736  0.92150   150261.0  1.08638e+08            NaN  浦发银行
101      2005-06-13 15:00:00  sse.600000  0.92150  0.93307  0.90094  0.91379    59609.0  4.23438e+07            NaN  浦发银行
102      2005-06-14 15:00:00  sse.600000  0.91765  0.92279  0.90608  0.90865    54629.0  3.88539e+07            NaN  浦发银行
103      2005-06-15 15:00:00  sse.600000  0.90608  0.90994  0.89323  0.89837    41288.0  2.88712e+07            NaN  浦发银行
104      2005-06-16 15:00:00  sse.600000  0.90094  0.94335  0.90094  0.94078   221679.0  1.60863e+08            NaN  浦发银行
105      2005-06-17 15:00:00  sse.600000  0.94335  0.96648  0.93178  0.95877   187577.0  1.39195e+08            NaN  浦发银行
106      2005-06-20 15:00:00  sse.600000  0.96648  0.98962  0.94978  0.97163   209778.0  1.58858e+08            NaN  浦发银行
107      2005-06-21 15:00:00  sse.600000  0.97548  0.99090  0.96391  0.97677   144592.0  1.10123e+08            NaN  浦发银行
108      2005-06-22 15:00:00  sse.600000  0.97291  0.99476  0.96906  0.99219   132548.0  1.01702e+08            NaN  浦发银行
109      2005-06-23 15:00:00  sse.600000  0.99604  0.99733  0.97034  0.97677    88286.0  6.74301e+07            NaN  浦发银行
110      2005-06-24 15:00:00  sse.600000  0.97034  0.98833  0.96006  0.97934   132683.0  1.00291e+08            NaN  浦发银行
111      2005-06-27 15:00:00  sse.600000  0.99604  1.00890  0.97677  0.98448   117669.0  9.11111e+07            NaN  浦发银行
112      2005-06-29 15:00:00  sse.600000  0.97677  0.97934  0.95749  0.96777    60142.0  4.53702e+07            NaN  浦发银行
113      2005-06-30 15:00:00  sse.600000  0.96520  1.00247  0.95235  0.98319    72035.0  5.41112e+07            NaN  浦发银行
114      2005-07-01 15:00:00  sse.600000  0.97420  0.97420  0.93950  0.94592    47086.0  3.47127e+07            NaN  浦发银行
115      2005-07-04 15:00:00  sse.600000  0.93821  0.95620  0.93307  0.95492    30880.0  2.27460e+07            NaN  浦发银行
116      2005-07-05 15:00:00  sse.600000  0.95492  0.96391  0.93821  0.95106    25782.0  1.91240e+07            NaN  浦发银行
117      2005-07-06 15:00:00  sse.600000  0.95492  0.96520  0.94849  0.95235    22130.0  1.64863e+07            NaN  浦发银行
118      2005-07-07 15:00:00  sse.600000  0.94849  0.96391  0.93950  0.94464    21416.0  1.58025e+07            NaN  浦发银行
119      2005-07-08 15:00:00  sse.600000  0.94464  0.94592  0.92536  0.92793    27017.0  1.96946e+07            NaN  浦发银行
120      2005-07-11 15:00:00  sse.600000  0.93950  0.95877  0.93821  0.94078    35030.0  2.58648e+07            NaN  浦发银行
121      2005-07-12 15:00:00  sse.600000  0.93821  1.03203  0.93178  1.01147   195931.0  1.52436e+08            NaN  浦发银行
122      2005-07-13 15:00:00  sse.600000  1.00247  1.00890  0.98833  0.99347    59279.0  4.60245e+07            NaN  浦发银行
123      2005-07-14 15:00:00  sse.600000  0.98962  1.01018  0.98705  0.99862    43116.0  3.36067e+07            NaN  浦发银行
124      2005-07-15 15:00:00  sse.600000  0.99990  1.01404  0.99733  1.00119    70777.0  5.53266e+07            NaN  浦发银行
125      2005-07-18 15:00:00  sse.600000  0.99604  1.01789  0.99219  1.01404    63640.0  4.98970e+07            NaN  浦发银行
126      2005-07-19 15:00:00  sse.600000  1.01404  1.04488  1.00633  1.01789   113747.0  9.09030e+07            NaN  浦发银行
127      2005-07-20 15:00:00  sse.600000  1.01532  1.03846  1.00890  1.01532    63990.0  5.08607e+07            NaN  浦发银行
128      2005-07-21 15:00:00  sse.600000  1.01789  1.02560  0.99733  1.01789    63858.0  5.00544e+07            NaN  浦发银行
129      2005-07-22 15:00:00  sse.600000  1.03075  1.06930  1.02303  1.05131   228374.0  1.86836e+08            NaN  浦发银行
130      2005-07-25 15:00:00  sse.600000  1.05388  1.07187  1.04360  1.06288   118444.0  9.79625e+07            NaN  浦发银行
131      2005-07-26 15:00:00  sse.600000  1.05645  1.09244  1.05516  1.06802   153659.0  1.28993e+08            NaN  浦发银行
132      2005-07-27 15:00:00  sse.600000  1.06673  1.07316  1.05002  1.06673    85428.0  7.04481e+07            NaN  浦发银行
133      2005-07-28 15:00:00  sse.600000  1.06673  1.07958  1.05388  1.06416    80139.0  6.66618e+07            NaN  浦发银行
134      2005-07-29 15:00:00  sse.600000  1.06159  1.07187  1.05388  1.07187    73487.0  6.08924e+07            NaN  浦发银行
135      2005-08-01 15:00:00  sse.600000  1.07059  1.07830  1.03974  1.04488    99844.0  8.16891e+07            NaN  浦发银行
136      2005-08-02 15:00:00  sse.600000  1.04103  1.05645  1.04103  1.05516    74603.0  6.08948e+07            NaN  浦发银行
137      2005-08-03 15:00:00  sse.600000  1.05645  1.07059  1.05259  1.05645    89787.0  7.42235e+07            NaN  浦发银行
138      2005-08-04 15:00:00  sse.600000  1.05388  1.06416  1.04617  1.05259    43280.0  3.54981e+07            NaN  浦发银行
139      2005-08-05 15:00:00  sse.600000  1.04874  1.08730  1.04745  1.08215   121315.0  1.01762e+08            NaN  浦发银行
140      2005-08-08 15:00:00  sse.600000  1.08730  1.10786  1.08601  1.08858    94712.0  8.07297e+07            NaN  浦发银行
141      2005-08-09 15:00:00  sse.600000  1.08601  1.09758  1.07444  1.09244    69336.0  5.85343e+07            NaN  浦发银行
142      2005-08-10 15:00:00  sse.600000  1.09244  1.12200  1.08601  1.11171    92126.0  7.95310e+07            NaN  浦发银行
143      2005-08-11 15:00:00  sse.600000  1.11171  1.13742  1.10657  1.12585   128609.0  1.12634e+08            NaN  浦发银行
144      2005-08-12 15:00:00  sse.600000  1.12714  1.13870  1.09115  1.09372   105416.0  9.11608e+07            NaN  浦发银行
145      2005-08-15 15:00:00  sse.600000  1.09501  1.11171  1.08987  1.11171    78476.0  6.71295e+07            NaN  浦发银行
146      2005-08-16 15:00:00  sse.600000  1.11557  1.13613  1.08344  1.09115   143836.0  1.24216e+08            NaN  浦发银行
147      2005-08-17 15:00:00  sse.600000  1.08601  1.10529  1.07316  1.09886   104592.0  8.83291e+07            NaN  浦发银行
148      2005-08-18 15:00:00  sse.600000  1.09886  1.10143  1.05131  1.05774   120574.0  1.01216e+08            NaN  浦发银行
149      2005-08-19 15:00:00  sse.600000  1.05388  1.08087  1.05388  1.07701    74688.0  6.22481e+07            NaN  浦发银行
150      2005-08-22 15:00:00  sse.600000  1.07701  1.08215  1.06031  1.07701    45005.0  3.75999e+07            NaN  浦发银行
151      2005-08-23 15:00:00  sse.600000  1.08087  1.08215  1.05774  1.06673    47106.0  3.91262e+07            NaN  浦发银行
152      2005-08-24 15:00:00  sse.600000  1.07316  1.09501  1.06802  1.08858   140069.0  1.18450e+08            NaN  浦发银行
153      2005-08-25 15:00:00  sse.600000  1.08601  1.10143  1.08215  1.09501    48080.0  4.08368e+07            NaN  浦发银行
154      2005-08-26 15:00:00  sse.600000  1.10272  1.11686  1.08858  1.09372    42414.0  3.61575e+07            NaN  浦发银行
155      2005-08-29 15:00:00  sse.600000  1.09372  1.10529  1.08601  1.08601    50493.0  4.30206e+07            NaN  浦发银行
156      2005-08-30 15:00:00  sse.600000  1.08601  1.09372  1.07958  1.08730    24791.0  2.09663e+07            NaN  浦发银行
157      2005-08-31 15:00:00  sse.600000  1.08215  1.09501  1.07958  1.08987    44416.0  3.75641e+07            NaN  浦发银行
158      2005-09-01 15:00:00  sse.600000  1.08987  1.11557  1.07830  1.10786    94492.0  8.06957e+07            NaN  浦发银行
159      2005-09-02 15:00:00  sse.600000  1.10529  1.11171  1.09886  1.10914    53723.0  4.62047e+07            NaN  浦发银行
160      2005-09-05 15:00:00  sse.600000  1.10914  1.11300  1.09758  1.10015    37592.0  3.23410e+07            NaN  浦发银行
161      2005-09-06 15:00:00  sse.600000  1.09758  1.09886  1.07701  1.07958    58419.0  4.94428e+07            NaN  浦发银行

In [25]:
count_trade

       name  close  is_ST
60    S佳通     3323      0
62    一汽富维    3455      0
64    万业企业    3203      0
65    万东医疗    3289      0
66    万华化学    3314      0
67    万向德农    3398      0
72    三一重工    3454      0
73    三元股份    3238      0
75    三友化工    3406      0
78    三峡新材    3286      0
79    三峡水利    3416      0
80    三房巷     3370      0
90    上实发展    3383      0
91    上工申贝    3318      0
93    上柴股份    3341      0
94    上汽集团    3396      0
95    上海三毛    3271      0
97    上海九百    3469      0
99    上海凤凰    3380      0
100   上海医药    3336      0
103   上海建工    3395      0
104   上海机场    3462      0
105   上海机电    3447      0
106   上海梅林    3354      0
109   上海物贸    3296      0
111   上海电力    3338      0
114   上海石化    3395      0
115   上海能源    3463      0
116   上海贝岭    3406      0
120   世茂股份    3406      0
124   东安动力    3422      0
127   东方创业    3402      0
132   东方电气    3340      0
134   东方航空    3311      0
136   东方通信    3457      0
139   东方集团    3308      0
143   东百集团    3419      0
144   东睦股份    3442      0
145   东软集团    3437      0
147   东风汽车    3409      0
148   东风科技    3444      0
150   两面针     3446      0
151   中体产业    3289      0
153   中信证券    3414      0
156   中储股份    3423      0
160   中化国际    3425      0
164   中原高速    3419      0
173   中国动力    3307      0
175   中国医药    3309      0
176   中国卫星    3441      0
179   中国国贸    3456      0
182   中国巨石    3410      0
191   中国石化    3457      0
195   中国联通    3365      0
196   中国船舶    3320      0
198   中国软件    3436      0
204   中国高科    3313      0
205   中天科技    3372      0
207   中央商场    3363      0
209   中恒集团    3388      0
212   中文传媒    3256      0
213   中新药业    3449      0
216   中材国际    3324      0
218   中油工程    3288      0
222   中炬高新    3372      0
224   中牧股份    3386      0
227   中直股份    3353      0
229   中粮糖业    3399      0
230   中航沈飞    3281      0
233   中航重机    3359      0
235   中船科技    3363      0
238   中视传媒    3358      0
240   中路股份    3363      0
243   中远海特    3342      0
244   中远海能    3347      0
246   中金黄金    3419      0
247   中铁工业    3381      0
249   中闽能源    3272      0
250   中青旅     3444      0
256   乐凯胶片    3429      0
257   乐山电力    3405      0
267   云煤能源    3224      0
269   五洲交通    3432      0
271   五矿发展    3266      0
272   五矿资本    3314      0
274   亚宝药业    3417      0
280   亚泰集团    3404      0
281   亚盛集团    3421      0
283   亚通股份    3438      0
285   交大昂立    3285      0
286   交运股份    3404      0
288   亨通光电    3333      0
290   京城股份    3244      0
291   京投发展    3394      0
292   京能电力    3307      0
293   京能置业    3426      0
295   人民同泰    3250      0
297   人福医药    3419      0
300   亿晶光电    3379      0
304   伊利股份    3408      0
305   伊力特     3460      0
314   保变电气    3342      0
315   保税科技    3258      0
319   信雅达     3293      0
322   健康元     3362      0
323   健民集团    3426      0
330   光大嘉宝    3429      0
333   光明乳业    3347      0
334   光明地产    3398      0
335   光电股份    3352      0
337   兖州煤业    3439      0
338   全柴动力    3421      0
340   八一钢铁    3286      0
341   六国化工    3452      0
342   兰太实业    3236      0
343   兰州民百    3298      0
344   兰生股份    3446      0
346   兰花科创    3458      0
351   兴发集团    3384      0
353   内蒙一机    3296      0
354   内蒙华电    3402      0
358   冠农股份    3406      0
359   冠城大通    3443      0
361   凌云股份    3296      0
362   凌钢股份    3370      0
364   凤凰光学    3260      0
365   凤凰股份    3248      0
366   凤竹纺织    3441      0
367   凯乐科技    3339      0
371   创业环保    3434      0
377   动力源     3436      0
379   包钢股份    3392      0
380   北京城乡    3440      0
381   北京城建    3431      0
383   北大荒     3402      0
384   北巴传媒    3403      0
385   北方导航    3242      0
386   北方稀土    3461      0
387   北方股份    3443      0
390   北矿科技    3431      0
393   千金药业    3444      0
394   华东电脑    3291      0
396   华仪电气    3325      0
398   华光股份    3312      0
400   华北制药    3435      0
401   华升股份    3426      0
403   华发股份    3414      0
404   华域汽车    3372      0
406   华夏幸福    3312      0
407   华夏银行    3409      0
410   华微电子    3425      0
413   华新水泥    3441      0
415   华泰股份    3447      0
417   华海药业    3440      0
418   华润双鹤    3396      0
419   华电国际    3422      0
422   华纺股份    3372      0
423   华联综超    3429      0
424   华胜天成    3354      0
425   华能国际    3443      0
429   华菱星马    3208      0
431   华谊集团    3350      0
433   华资实业    3257      0
435   华远地产    3237      0
436   华鑫股份    3386      0
439   华银电力    3340      0
440   华鲁恒升    3449      0
442   卓郎智能    3330      0
443   南京化纤    3419      0
444   南京医药    3422      0
446   南京熊猫    3342      0
449   南京高科    3442      0
452   南宁百货    3425      0
453   南山铝业    3343      0
455   南方航空    3404      0
456   南纺股份    3274      0
458   南钢股份    3386      0
459   博信股份    3208      0
463   博汇纸业    3402      0
468   博闻科技    3458      0
470   卧龙电驱    3365      0
473   厦门国贸    3443      0
474   厦门空港    3464      0
476   厦门钨业    3440      0
477   友好集团    3329      0
478   双良节能    3317      0
480   古越龙山    3452      0
482   号百控股    3318      0
496   同仁堂     3471      0
497   同方股份    3285      0
499   同济科技    3451      0
500   同达创业    3353      0
504   哈投股份    3273      0
506   哈空调     3346      0
507   哈药股份    3231      0
508   哈高科     3404      0
513   嘉化能源    3248      0
518   四创电子    3313      0
520   四川路桥    3371      0
522   四川长虹    3399      0
528   国发股份    3278      0
529   国投中鲁    3331      0
530   国投电力    3312      0
531   国投资本    3311      0
535   国机通用    3276      0
539   国电南瑞    3294      0
540   国电南自    3406      0
541   国电电力    3343      0
542   国睿科技    3393      0
545   国药股份    3285      0
546   国金证券    3346      0
547   圆通速递    3372      0
555   城市传媒    3310      0
559   士兰微     3384      0
560   复旦复华    3454      0
561   复星医药    3431      0
562   外高桥     3318      0
565   大东方     3438      0
567   大众交通    3449      0
568   大众公用    3408      0
575   大唐电信    3242      0
576   大商股份    3380      0
577   大恒科技    3391      0
580   大有能源    3330      0
581   大湖股份    3266      0
584   大西洋     3356      0
586   大连圣亚    3387      0
588   大连热电    3264      0
589   大龙地产    3448      0
593   天地源     3444      0
594   天地科技    3395      0
595   天坛生物    3285      0
597   天士力     3440      0
599   天宸股份    3387      0
600   天富能源    3417      0
602   天房发展    3449      0
605   天津港     3437      0
610   天科股份    3269      0
611   天药股份    3359      0
612   天通股份    3332      0
617   太化股份    3356      0
618   太原重工    3436      0
621   太极实业    3300      0
622   太极集团    3300      0
623   太龙药业    3367      0
628   好当家     3447      0
631   妙可蓝多    3211      0
636   宁夏建材    3389      0
637   宁沪高速    3433      0
638   宁波中百    3387      0
...     ...    ...    ...
890   曲江文旅    3368      0
892   有研新材    3368      0
895   杉杉股份    3418      0
898   杭州解百    3330      0
901   杭萧钢构    3383      0
902   杭钢股份    3378      0
907   林海股份    3276      0
911   标准股份    3438      0
912   栖霞建设    3328      0
913   株冶集团    3425      0
914   格力地产    3381      0
916   桂东电力    3441      0
917   桂冠电力    3315      0
920   梅花生物    3246      0
922   梅雁吉祥    3363      0
926   楚天高速    3279      0
928   欧亚集团    3441      0
932   歌华有线    3438      0
938   武汉控股    3249      0
940   民丰特纸    3445      0
941   民生银行    3451      0
942   氯碱化工    3448      0
943   水井坊     3441      0
954   永鼎股份    3371      0
957   汇通能源    3370      0
960   汇鸿集团    3281      0
961   汉商集团    3436      0
962   江中药业    3360      0
965   江南高纤    3454      0
967   江山股份    3311      0
970   江淮汽车    3335      0
971   江苏吴中    3357      0
975   江苏索普    3367      0
976   江苏舜天    3421      0
978   江苏阳光    3444      0
979   江西铜业    3429      0
980   江西长运    3387      0
982   沧州大化    3386      0
984   法拉电子    3464      0
986   波导股份    3452      0
990   泰豪科技    3224      0
994   津劝业     3397      0
995   洪城水业    3319      0
996   洪都航空    3374      0
999   济川药业    3334      0
1002  浙大网新    3314      0
1004  浙江东方    3268      0
1005  浙江东日    3232      0
1007  浙江医药    3432      0
1008  浙江富润    3353      0
1011  浙江龙盛    3421      0
1013  浦东建设    3392      0
1014  浦东金桥    3401      0
1015  浦发银行    3399      0
1016  浪潮软件    3335      0
1017  浪莎股份    3327      0
1018  海信电器    3445      0
1028  海欣股份    3428      0
1029  海正药业    3407      0
1031  海油工程    3453      0
1032  海泰发展    3417      0
1033  海澜之家    3387      0
1034  海立股份    3372      0
1035  海航创新    3297      0
1037  海航控股    3255      0
1039  海螺水泥    3449      0
1040  海越能源    3318      0
1041  海通证券    3389      0
1045  涪陵电力    3382      0
1046  淮北矿业    3225      0
1049  深高速     3447      0
1052  渤海汽车    3285      0
1054  湖南海利    3426      0
1057  湘电股份    3377      0
1058  湘邮科技    3438      0
1061  澄星股份    3390      0
1062  澳柯玛     3421      0
1064  瀚蓝环境    3379      0
1067  烽火通信    3410      0
1068  熊猫金控    3205      0
1073  片仔癀     3444      0
1075  物产中大    3250      0
1076  特变电工    3333      0
1078  王府井     3258      0
1080  现代制药    3335      0
1084  珠江实业    3463      0
1087  瑞贝卡     3449      0
1089  生物股份    3423      0
1090  生益科技    3430      0
1091  用友网络    3446      0
1092  申华控股    3219      0
1093  申能股份    3453      0
1094  申达股份    3411      0
1095  申通地铁    3384      0
1096  电子城     3412      0
1099  界龙实业    3453      0
1100  白云山     3271      0
1101  白云机场    3453      0
1105  百利电气    3201      0
1108  百大集团    3362      0
1110  百联股份    3340      0
1117  皖维高新    3383      0
1118  皖通高速    3448      0
1120  益佰制药    3442      0
1121  益民集团    3459      0
1122  盘江股份    3370      0
1127  石化油服    3279      0
1131  祁连山     3416      0
1133  神奇制药    3367      0
1134  神马股份    3383      0
1137  祥龙电业    3253      0
1138  福建水泥    3454      0
1139  福建高速    3463      0
1140  福成股份    3291      0
1143  福田汽车    3413      0
1144  福耀玻璃    3450      0
1145  福能股份    3367      0
1152  科力远     3236      0
1157  科达洁能    3229      0
1158  科达股份    3258      0
1161  空港股份    3434      0
1163  第一医药    3456      0
1164  粤泰股份    3210      0
1165  精伦电子    3375      0
1166  精工钢构    3413      0
1167  精达股份    3213      0
1169  紫江企业    3436      0
1172  红星发展    3466      0
1174  红豆股份    3333      0
1175  红阳能源    3326      0
1182  维科技术    3365      0
1183  维维股份    3416      0
1184  综艺股份    3374      0
1190  置信电气    3317      0
1191  美克家居    3391      0
1193  美尔雅     3397      0
1196  美都能源    3252      0
1197  羚锐制药    3412      0
1200  耀皮玻璃    3314      0
1201  老凤祥     3418      0
1202  老白干酒    3206      0
1204  联创光电    3318      0
1207  联环药业    3420      0
1208  联美控股    3252      0
1210  腾达建设    3381      0
1214  舍得酒业    3408      0
1216  航发科技    3424      0
1217  航天信息    3313      0
1218  航天动力    3432      0
1220  航天晨光    3441      0
1221  航天机电    3229      0
1222  航天电子    3355      0
1223  航天通信    3319      0
1224  航天长峰    3282      0
1225  航民股份    3399      0
1237  苏州高新    3332      0
1241  茂业商业    3229      0
1243  荣华实业    3292      0
1248  莫高股份    3427      0
1252  营口港     3381      0
1253  葛洲坝     3401      0
1257  西宁特钢    3362      0
1259  西昌电力    3401      0
1260  西水股份    3222      0
1261  西藏城投    3235      0
1262  西藏天路    3438      0
1265  西藏药业    3272      0
1269  览海投资    3279      0
1278  豫光金铅    3430      0
1284  贵州茅台    3433      0
1286  贵研铂业    3434      0
1287  贵绳股份    3464      0
1288  贵航股份    3367      0
1293  赣粤高速    3419      0
1297  轻纺城     3285      0
1298  辅仁药业    3317      0
1300  辽宁成大    3289      0
1302  远达环保    3370      0
1306  迪马股份    3230      0
1307  通化东宝    3407      0
1308  通威股份    3301      0
1311  通策医疗    3284      0
1315  郑州煤电    3321      0
1317  郴电国际    3451      0
1318  鄂尔多斯    3294      0
1319  酒钢宏兴    3423      0
1321  重庆啤酒    3373      0
1324  重庆港九    3379      0
1327  重庆路桥    3349      0
1329  金健米业    3386      0
1330  金发科技    3360      0
1331  金地集团    3378      0
1334  金晶科技    3434      0
1335  金杯汽车    3225      0
1336  金枫酒业    3424      0
1341  金瑞矿业    3234      0
1343  金种子酒    3423      0
1345  金自天正    3461      0
1346  金花股份    3410      0
1347  金证股份    3326      0
1354  金鹰股份    3289      0
1356  金龙汽车    3356      0
1357  钱江水利    3441      0
1358  钱江生化    3223      0
1360  铁龙物流    3455      0
1361  铜峰电子    3377      0
1362  银座股份    3314      0
1364  银鸽投资    3308      0
1366  锦州港     3420      0
1367  锦江投资    3455      0
1368  锦江股份    3300      0
1371  长园集团    3216      0
1374  长城电工    3451      0
1376  长春一东    3292      0
1377  长春燃气    3412      0
1378  长春经开    3347      0
1381  长江通信    3408      0
1387  阳光照明    3459      0
1388  阳泉煤业    3453      0
1392  陆家嘴     3340      0
1398  隧道股份    3378      0
1399  雅戈尔     3391      0
1403  青山纸业    3368      0
1404  青岛啤酒    3415      0
1405  青岛海尔    3348      0
1407  青松建化    3428      0
1408  青海华鼎    3334      0
1415  风神股份    3271      0
1418  飞乐音响    3363      0
1420  首创股份    3421      0
1421  首商股份    3412      0
1422  首开股份    3369      0
1424  香梨股份    3207      0
1425  香江控股    3316      0
1426  香溢融通    3443      0
1428  马应龙     3466      0
1429  马钢股份    3442      0
1430  驰宏锌锗    3212      0
1433  鲁信创投    3298      0
1435  鲁商置业    3367      0
1436  鲁抗医药    3450      0
1439  鹏博士     3370      0
1443  黄山旅游    3444      0
1444  黄河旋风    3390      0
1445  黑牡丹     3399      0
1448  龙元建设    3441      0
1449  龙净环保    3439      0
1450  龙头股份    3461      0
1452  龙建股份    3420      0
1454  龙溪股份    3387      0

[601 rows x 3 columns]